"""共享协议：Agent 基类、事件、StructuredIntent。"""

from .base import Agent
from .events import (
    AgentEvent,
    ErrorEvent,
    ExecutionResultEvent,
    FinalAnswerEvent,
    HubPhaseEvent,
    HubTurnCompleteEvent,
    IntentOutcomeEvent,
    MemoryConsolidatedEvent,
    PlanCreatedEvent,
    PlanReadyEvent,
    PlanTextDeltaEvent,
    ReflectionCompleteEvent,
    ReflectionStartEvent,
    ReflectionTextDeltaEvent,
    RunStatsEvent,
    StepCompleteEvent,
    StepErrorEvent,
    StepOutputDeltaEvent,
    StepStartEvent,
    TextDeltaEvent,
    ToolCallEvent,
    ToolResultEvent,
)
from .intent import StructuredIntent, parse_intent_from_answer

__all__ = [
    "Agent",
    "AgentEvent",
    "StructuredIntent",
    "parse_intent_from_answer",
    "TextDeltaEvent",
    "FinalAnswerEvent",
    "ErrorEvent",
    "ToolCallEvent",
    "ToolResultEvent",
    "RunStatsEvent",
    "IntentOutcomeEvent",
    "MemoryConsolidatedEvent",
    "PlanCreatedEvent",
    "PlanReadyEvent",
    "PlanTextDeltaEvent",
    "StepStartEvent",
    "StepOutputDeltaEvent",
    "StepCompleteEvent",
    "StepErrorEvent",
    "ExecutionResultEvent",
    "HubPhaseEvent",
    "HubTurnCompleteEvent",
    "ReflectionStartEvent",
    "ReflectionTextDeltaEvent",
    "ReflectionCompleteEvent",
]
